[package]
name = "quines"
version = "0.1.0"
authors = ["Tekkac <tekkac@proton.me>"]
description = "A set of quines in Cairo"
keywords = ["self-replicating", "quine", "cairo", "starknet"]
edition = "2024_07"


[dependencies]

[dev-dependencies]
cairo_test = ">=2.8.2"

[scripts]
isquine = "python scripts/is_cairo_quine.py"
